name: Linter

on:
  push:
    branches: [main, develop]

  pull_request:
    branches: [main, develop]

jobs:
  flake8_py3:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64

      - name: Checkout code
        uses: actions/checkout@master

      - name: Cache dependency # caching dependency will make our build faster.
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install requirements
        run: pip install -r src/requirements.txt

      - name: ⭐ Análise das importações usando o linter `isort`
        run: |
          pip install isort==5.10.1
          isort --check-only src/

      # - name: ⭐⭐ Análise folha de estilo com o linter `black`
      #   run: |
      #     pip install black==22.6.0
      #     black --check src/

      - name: Install flake8
        run: pip install flake8

      - name: ⭐⭐⭐ Análise folha de estilo com o linter `flake8`
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: "flake8_py3" # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ⭐⭐⭐⭐ Análise do código com o linter `pylint`
        run: |
          pip install pylint-django==2.4.4
          cd src && pylint $(git ls-files '*.py')


