name: Run Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.10.5
          cache: pip

      # caching dependency will make our build faster.
      - name: Cache dependency
        uses: actions/cache@master
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # - name: Install tox
      #   run: pip install tox

      # - name: Run tests
      #   run: tox -- --cov=src --cov-report=xml --junitxml=junittest.xml

      - name: Install requirements
        run: pip install -r src/requirements.txt

      - name: Run Migrations
        run: python src/manage.py migrate

      # coverage report --fail-under=50
      - name: Análise de cobertura de testes
        run: |
          pip install coverage==6.4.2
          coverage run -m pytest src --junitxml=./src/reports/junit.xml
          coverage xml -o src/reports/coverage.xml

      # Análise da base de código
      - name: SonarCloud Scan
        if: always()
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # sed -i 's/\/home\/runner\/work\/2022-1-MeasureSoftGram-Service\/2022-1-MeasureSoftGram-Service/\/github\/workspace\//g' src/reports/coverage.xml
      - name: fix code coverage paths
        if: always()
        run: |
          sed -i 's/<source>\/home\/runner\/work\/2022-1-MeasureSoftGram-Service\/2022-1-MeasureSoftGram-Service<\/source>/<source>\/github\/workspace<\/source>/g' src/reports/coverage.xml

      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@master
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./src/reports/coverage.xml
          flags: unittests
          name: 2022-1-MeasureSoftGram-Service
          verbose: true
